### ISSUE TITLE
Latest builds fail due to broken folium requirement.

### ISSUE THREAD

**Issue by danschef** [conda-forge/sicor-feedstock#14]
Issue:

The build process on Azure fails with `arosics 1.2.4 has requirement folium>=0.6.0, but you have folium 0.0.0.` This is due to a broken folium release as already reported here: https://github.com/python-visualization/folium/issues/1438

**Comment by niklasbohn** [comment]
Pinning `folium>=0.6.0,!=0.12.0` in the `meta.yaml` file at least temporarily fixed the build process on Azure.

**Comment by danschef** [comment]
Right, but as soon as [this](https://github.com/conda-forge/arosics-feedstock/pull/24) is merged, it should not be needed anymore.

**Comment by danschef** [comment]
Can this be closed now? The above mentioned PR was merged and folium 0.12.1 is released.

**Comment by niklasbohn** [comment]
You're totally right. I close the issue.
